// ADHIPRAMA E-VOTING - frontend offline/local prototype
const ADMIN_PIN = "1234"; // ganti sebelum dipakai resmi
const STORAGE_KEY = "adhiprama_votes_v2";
const PROFILE_STORAGE_KEY = "adhiprama_voter_profiles_v1";

// Nomor urut TETAP. Yang diacak hanya posisi kartu di layar.
const candidatesKetua = [
 {id:"k1",number:"01",name:"Raden Arya Wicaksana",class:"XI MIPA 1",origin:"Sunda-Jawa",motto:"Nyantrik, Nyantri, Nyeni ing Paripurna",photo:avatar("#f3e0d0","#4a0e17","01"),visi:"Mewujudkan OSIS ADHIPRAMA sebagai sarana kepemimpinan berintegritas tinggi, berwawasan global, serta teguh menjaga etika luhur budaya Jawa dan Sunda.",misi:["Meningkatkan solidaritas antar siswa.","Mengintegrasikan teknologi ramah pengguna.","Mengadakan panggung ekspresi budaya dan bakat siswa."],programs:["Festival Budaya Nusantara","OSIS Digital Hub","Mentoring Sebaya"]},
 {id:"k2",number:"02",name:"Nyi Mas Galuh Prameshwari",class:"XI IPS 2",origin:"Sunda",motto:"Silih Asah, Silih Asih, Silih Asuh",photo:avatar("#f8ecd1","#7a1c28","02"),visi:"Menjadikan OSIS wadah yang inklusif, responsif, dan mencetak siswa berteladan unggul.",misi:["Menampung aspirasi siswa secara transparan.","Mengembangkan kepedulian sosial.","Memperkuat kedisiplinan dan kepemimpinan."],programs:["Leadership Camp","Green School","Pojok Karya Siswa"]},
 {id:"k3",number:"03",name:"Bagus Satria Ananta",class:"XI MIPA 3",origin:"Jawa",motto:"Jer Basuki Mawa Beya",photo:avatar("#e7ead6","#61141f","03"),visi:"Membawa OSIS ADHIPRAMA menjadi pelopor inovasi akademik dan non-akademik berlandaskan kekeluargaan.",misi:["Mengoptimalkan kompetensi siswa.","Membangun komunikasi antar kelas.","Menciptakan ruang apresiasi bakat."],programs:["Youth Innovation Summit","Pekan Olahraga & Seni","Aspirasi Karsa"]},
 {id:"k4",number:"04",name:"Kandidat Ketua 4",class:"XI TKJ B",origin:"Jawa-Sunda",motto:"Rukun, Raket, Sauyunan",photo:avatar("#eee1c9","#8b6917","04"),visi:"Mewujudkan kepemimpinan siswa yang adaptif, santun, kreatif, dan menjunjung solidaritas.",misi:["Memperkuat kerja sama siswa.","Membuka ruang kreativitas.","Menumbuhkan budaya disiplin."],programs:["Ruang Aspirasi","Pekan Kreativitas","Gerakan Sauyunan"]}
];
const candidatesWakil = [
 {id:"w1",number:"01",name:"Siti Dewi Lestari",class:"X MIPA 2",origin:"Sunda",motto:"Tatap, Tapa, Matapa",photo:avatar("#f3dfdf","#4a0e17","01"),visi:"Mendampingi kepemimpinan OSIS dengan tata kelola yang solid, terbuka, dan sigap.",misi:["Memperbaiki administrasi.","Menjalin komunikasi harmonis.","Mendukung kegiatan ekstrakurikuler."],programs:["Open Dashboard","Klinik Organisasi","Literasi Digital"]},
 {id:"w2",number:"02",name:"Dimas Aji Pangestu",class:"X IPS 1",origin:"Jawa",motto:"Akur Rukun Hambangun Karya",photo:avatar("#e9dfcf","#61141f","02"),visi:"Menjadi jembatan solidaritas yang kuat antar angkatan dan mempererat persaudaraan.",misi:["Merangkul seluruh elemen siswa.","Mengadakan kegiatan kebersamaan.","Menjaga suasana sekolah kondusif."],programs:["Forum Lintas Kelas","E-Sports & Art League","Bhakti Sosial"]},
 {id:"w3",number:"03",name:"Asep Saepullah Tirta",class:"X MIPA 1",origin:"Sunda",motto:"Sarendeu Saigel Sabobot Sapihanean",photo:avatar("#f2e7cc","#8b6917","03"),visi:"Mewujudkan pendampingan OSIS yang cekatan, tanggap isu sosial, serta berakhlak mulia.",misi:["Layanan konseling sebaya.","Aksi kepedulian lingkungan.","Menumbuhkan keteladanan harian."],programs:["Peer Counselor","Gerakan Resik & Asri","Duta Keteladanan"]}
];

let currentVoter=null, selectedKetuaId=null, selectedWakilId=null, chairOrder=[], viceOrder=[];
const $=id=>document.getElementById(id);
function avatar(bg,accent,num){
 return `data:image/svg+xml;charset=UTF-8,${encodeURIComponent(`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 600 600"><rect width="600" height="600" fill="${bg}"/><circle cx="300" cy="290" r="230" fill="none" stroke="${accent}" stroke-width="14" opacity=".25"/><path d="M90 540c30-150 120-210 210-210s180 60 210 210" fill="${accent}"/><circle cx="300" cy="245" r="105" fill="#d6a77d"/><path d="M185 220c20-120 210-140 235 0-50-38-170-40-235 0" fill="${accent}"/><path d="M230 350q70 55 140 0" fill="none" stroke="#d4af37" stroke-width="15"/><text x="300" y="505" text-anchor="middle" font-family="Georgia" font-size="48" font-weight="700" fill="#d4af37">NO. ${num}</text></svg>`)}`;
}
function getVotes(){try{return JSON.parse(localStorage.getItem(STORAGE_KEY)||"[]")}catch{return[]}}
function saveVote(v){const votes=getVotes();votes.push(v);localStorage.setItem(STORAGE_KEY,JSON.stringify(votes))}
function saveVoterProfile(profile){const rows=getVoterProfiles();rows.push(profile);localStorage.setItem(PROFILE_STORAGE_KEY,JSON.stringify(rows))}
function getVoterProfiles(){try{return JSON.parse(localStorage.getItem(PROFILE_STORAGE_KEY)||"[]")}catch{return[]}}
function hasVoted(nis){return getVotes().some(v=>String(v.nis)===String(nis))}
function showView(id){document.querySelectorAll('.view').forEach(v=>v.classList.remove('active'));$(id).classList.add('active');document.body.classList.toggle('admin-view',id==='view-admin');window.scrollTo({top:0,behavior:'smooth'})}
function renderCards(){
 $('ketua-grid').innerHTML=chairOrder.map(c=>card(c,'ketua')).join('');
 $('wakil-grid').innerHTML=viceOrder.map(c=>card(c,'wakil')).join('');
}
function card(c,role){const selected=role==='ketua'?selectedKetuaId===c.id:selectedWakilId===c.id;return `<article class="candidate-card ${selected?'selected':''}"><div class="photo-wrap"><img src="${c.photo}" alt="Kandidat ${c.number}"><span class="number-badge">URUT ${c.number}</span></div><div class="candidate-body"><h3>${c.name}</h3><div class="candidate-meta">${c.class} · ${c.origin}</div><div class="motto">“${c.motto}”</div><p class="visi"><b>Visi:</b> ${c.visi}</p></div><div class="candidate-actions"><button class="detail-btn" data-detail="${c.id}" data-role="${role}">LIHAT VISI, MISI & PROGRAM</button><button class="select-btn" data-select="${c.id}" data-role="${role}">${selected?'✓ TERPILIH':'PILIH KANDIDAT'}</button></div></article>`}
function findCandidate(id,role){return(role==='ketua'?candidatesKetua:candidatesWakil).find(c=>c.id===id)}
function selectCandidate(id,role){if(role==='ketua')selectedKetuaId=id;else selectedWakilId=id;updateSummary();renderCards();if(role==='ketua'&&!selectedWakilId)switchTab('wakil')}
function updateSummary(){const k=findCandidate(selectedKetuaId,'ketua'),w=findCandidate(selectedWakilId,'wakil');$('selection-summary').textContent=`Ketua: ${k?`No. ${k.number} - ${k.name}`:'—'}  |  Wakil: ${w?`No. ${w.number} - ${w.name}`:'—'}`;$('submit-vote').disabled=!(k&&w)}
function switchTab(tab){$('tab-ketua').classList.toggle('active',tab==='ketua');$('tab-wakil').classList.toggle('active',tab==='wakil');$('content-ketua').classList.toggle('hidden',tab!=='ketua');$('content-wakil').classList.toggle('hidden',tab!=='wakil')}
function openConfirm(){const k=findCandidate(selectedKetuaId,'ketua'),w=findCandidate(selectedWakilId,'wakil');if(!k||!w)return;$('confirm-ketua').textContent=`No. ${k.number} - ${k.name}`;$('confirm-wakil').textContent=`No. ${w.number} - ${w.name}`;$('modal-confirm').classList.remove('hidden')}
function closeModal(id){$(id).classList.add('hidden')}
let homeRedirectTimer=null,countdownTimer=null;
function submitVote(){const k=findCandidate(selectedKetuaId,'ketua'),w=findCandidate(selectedWakilId,'wakil');saveVote({timestamp:new Date().toISOString(),ketuaId:k.id,wakilId:w.id});saveVoterProfile({name:currentVoter.name,type:currentVoter.type,classMajor:currentVoter.classMajor});closeModal('modal-confirm');showView('view-success');let seconds=5;$('countdown-number').textContent=seconds;$('countdown-label').textContent=`${seconds} detik`;clearInterval(countdownTimer);countdownTimer=setInterval(()=>{seconds--;if(seconds<=0){clearInterval(countdownTimer);return}$('countdown-number').textContent=seconds;$('countdown-label').textContent=`${seconds} detik`},1000);clearTimeout(homeRedirectTimer);homeRedirectTimer=setTimeout(resetForNext,5000)}
function resetForNext(){clearTimeout(homeRedirectTimer);clearInterval(countdownTimer);currentVoter=null;selectedKetuaId=null;selectedWakilId=null;$('voter-form').reset();$('class-major-field').classList.add('hidden');$('voter-class-major').required=false;showView('view-login')}
function renderAdmin(){
 const votes=getVotes();$('stat-total').textContent=votes.length;$('stat-ketua-total').textContent=votes.length;$('stat-wakil-total').textContent=votes.length;
 renderVoterProfiles();
 const kc=Object.fromEntries(candidatesKetua.map(c=>[c.id,0])),wc=Object.fromEntries(candidatesWakil.map(c=>[c.id,0]));votes.forEach(v=>{if(kc[v.ketuaId]!==undefined)kc[v.ketuaId]++;if(wc[v.wakilId]!==undefined)wc[v.wakilId]++});
 renderResultList('ketua-results',candidatesKetua,kc);renderResultList('wakil-results',candidatesWakil,wc);
 const kw=winner(candidatesKetua,kc),ww=winner(candidatesWakil,wc);fillWinner('ketua',kw,votes.length);fillWinner('wakil',ww,votes.length);
 let conclusion='Belum ada suara yang masuk.';if(votes.length){const ktxt=kw.tie?`Ketua masih seri: ${kw.items.map(x=>`No. ${x.number} ${x.name}`).join(' dan ')}`:`Ketua terpilih: No. ${kw.item.number} ${kw.item.name} (${kw.max} suara)`;const wtxt=ww.tie?`Wakil masih seri: ${ww.items.map(x=>`No. ${x.number} ${x.name}`).join(' dan ')}`:`Wakil terpilih: No. ${ww.item.number} ${ww.item.name} (${ww.max} suara)`;conclusion=`${ktxt}. ${wtxt}. Perhitungan dilakukan otomatis berdasarkan seluruh suara yang tersimpan di perangkat ini.`}$('overall-conclusion').innerHTML=conclusion}
function renderVoterProfiles(){const root=$('voter-profile-results'),profiles=getVoterProfiles();root.replaceChildren();if(!profiles.length){const empty=document.createElement('p');empty.className='muted';empty.textContent='Belum ada data pemilih.';root.append(empty);return}profiles.forEach(p=>{const row=document.createElement('div'),name=document.createElement('strong'),details=document.createElement('span');row.className='profile-row';name.textContent=p.name||'Nama tidak tersedia';details.textContent=p.classMajor?`${p.type} · ${p.classMajor}`:(p.type||'Tidak diketahui');row.append(name,details);root.append(row)})}
function winner(list,counts){let max=Math.max(...list.map(c=>counts[c.id]),0);const items=list.filter(c=>counts[c.id]===max);return{item:items[0],items,max,tie:max>0&&items.length>1}}
function fillWinner(role,res,total){const p=role==='ketua'?'winner-ketua':'winner-wakil';if(!res.item||!total){$(p+'-number').textContent='—';$(p+'-name').textContent='Belum ada suara';$(p+'-votes').textContent='0 suara';return}if(res.tie){$(p+'-number').textContent='SERI';$(p+'-name').textContent=res.items.map(x=>`No. ${x.number} ${x.name}`).join(' / ');$(p+'-votes').textContent=`${res.max} suara masing-masing`;return}$(p+'-number').textContent=`NO. ${res.item.number}`;$(p+'-name').textContent=res.item.name;$(p+'-votes').textContent=`${res.max} suara`}
function renderResultList(target,list,counts){const total=getVotes().length;$(target).innerHTML=list.map(c=>{const n=counts[c.id],pct=total?Math.round(n/total*100):0;return `<div class="result-row ${n===Math.max(...list.map(x=>counts[x.id]))&&n>0?'winner':''}"><div class="result-top"><span>No. ${c.number} · ${c.name}</span><span>${n} suara · ${pct}%</span></div><div class="bar"><span style="width:${pct}%"></span></div></div>`}).join('')}
function exportCSV(){const votes=getVotes();if(!votes.length){alert('Belum ada suara.');return}const kc=Object.fromEntries(candidatesKetua.map(c=>[c.id,0])),wc=Object.fromEntries(candidatesWakil.map(c=>[c.id,0]));votes.forEach(v=>{kc[v.ketuaId]++;wc[v.wakilId]++});let csv='Posisi,Nomor,Nama,Suara,Persentase\n';candidatesKetua.forEach(c=>csv+=`Ketua,${c.number},"${c.name}",${kc[c.id]},${Math.round(kc[c.id]/votes.length*100)}%\n`);candidatesWakil.forEach(c=>csv+=`Wakil,${c.number},"${c.name}",${wc[c.id]},${Math.round(wc[c.id]/votes.length*100)}%\n`);const a=document.createElement('a');a.href='data:text/csv;charset=utf-8,'+encodeURIComponent(csv);a.download='Hasil_Keseluruhan_ADHIPRAMA.csv';a.click()}
function resetVotes(){$('reset-password').value='';$('modal-reset').classList.remove('hidden');setTimeout(()=>$('reset-password').focus(),50)}
function confirmResetVotes(){if($('reset-password').value==='1234'){localStorage.removeItem(STORAGE_KEY);localStorage.removeItem(PROFILE_STORAGE_KEY);closeModal('modal-reset');renderAdmin()}else{alert('Password salah. Data tidak dihapus.');$('reset-password').focus()}}
function openAdmin(){ $('admin-pin').value='';$('modal-admin').classList.remove('hidden');setTimeout(()=>$('admin-pin').focus(),50)}
function verifyAdmin(){if($('admin-pin').value===ADMIN_PIN){closeModal('modal-admin');showView('view-admin');renderAdmin()}else alert('PIN admin salah.')}
function detail(id,role){const c=findCandidate(id,role);alert(`NO. ${c.number} - ${c.name}\n\nVisi:\n${c.visi}\n\nMisi:\n- ${c.misi.join('\n- ')}\n\nProgram:\n- ${c.programs.join('\n- ')}`)}

$('voter-type').addEventListener('change',()=>{const type=$('voter-type').value,needsDetails=type==='Siswa'||type==='Guru';$('class-major-field').classList.toggle('hidden',!needsDetails);$('class-major-field').firstChild.textContent=type==='Guru'?'Unit / Bidang':'Kelas / Jurusan';$('voter-class-major').required=needsDetails});
$('voter-form').addEventListener('submit',e=>{e.preventDefault();const name=$('voter-name').value.trim(),type=$('voter-type').value,classMajor=$('voter-class-major').value.trim();if(!name||!type||((type==='Siswa'||type==='Guru')&&!classMajor))return;currentVoter={name,type,classMajor};$('display-voter').textContent=classMajor?`${name} · ${classMajor}`:`${name} · ${type}`;selectedKetuaId=null;selectedWakilId=null;chairOrder=candidatesKetua;viceOrder=candidatesWakil;renderCards();updateSummary();switchTab('ketua');showView('view-voting')});
$('ketua-grid').addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.select)selectCandidate(b.dataset.select,b.dataset.role);if(b.dataset.detail)detail(b.dataset.detail,b.dataset.role)});
$('wakil-grid').addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.select)selectCandidate(b.dataset.select,b.dataset.role);if(b.dataset.detail)detail(b.dataset.detail,b.dataset.role)});
$('tab-ketua').onclick=()=>switchTab('ketua');$('tab-wakil').onclick=()=>switchTab('wakil');$('submit-vote').onclick=openConfirm;$('confirm-cancel').onclick=()=>closeModal('modal-confirm');$('confirm-send').onclick=submitVote;$('admin-cancel').onclick=()=>closeModal('modal-admin');$('admin-login').onclick=verifyAdmin;$('admin-exit').onclick=()=>showView('view-login');$('export-btn').onclick=exportCSV;$('reset-btn').onclick=resetVotes;$('reset-cancel').onclick=()=>closeModal('modal-reset');$('reset-confirm').onclick=confirmResetVotes;

// Shortcut khusus panitia: Ctrl+C lalu B dalam waktu 1,2 detik. Tidak ada tombol Hasil di halaman pemilih.
let adminSequence=false,sequenceTimer=null;document.addEventListener('keydown',e=>{const key=e.key.toLowerCase();if(document.body.classList.contains('admin-view')&&e.ctrlKey&&e.shiftKey&&key==='v'){e.preventDefault();showView('view-login');return}if(e.ctrlKey&&key==='c'){e.preventDefault();adminSequence=true;clearTimeout(sequenceTimer);sequenceTimer=setTimeout(()=>adminSequence=false,1200);return}if(adminSequence&&key==='b'){e.preventDefault();adminSequence=false;clearTimeout(sequenceTimer);openAdmin()}});

// ESC hanya menutup modal, bukan keluar dari aplikasi.
document.addEventListener('keydown',e=>{if(e.key==='Escape'){['modal-confirm','modal-admin','modal-reset'].forEach(id=>$(id).classList.add('hidden'))}});
